import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Suspense } from "react";
import ThemeToggle from "./components/ThemeToggle";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex flex-col justify-center min-h-screen items-center my-5 relative">
      {/* Logo */}
      <Link href={"/sign-in"}>
        <Image
          src={"/assets/logo.png"}
          alt="logo"
          width={100}
          height={75}
          className="absolute top-2 left-2"
        />
      </Link>

      <ThemeToggle />

      {/* Content */}
      <Suspense fallback={<div>Loading...</div>}>
        {children}
      </Suspense>
    </section>
  );
}
