import ThemeToggle from "@/components/ThemeToggle";
import Loader from "@/components/ui/loader";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex flex-col justify-center min-h-screen items-center relative dark:bg-dark-bg">
      {/* Logo */}
      <Link href={"/"}>
        <Image
          src={"/assets/logo.png"}
          alt="logo"
          width={100}
          height={75}
          className="absolute top-2 left-2"
        />
      </Link>

      <ThemeToggle />

      {/* Content */}
      <Suspense
        fallback={
          <div className="flex justify-center items-center h-screen">
            <Loader size="lg" text="Loading..." />
          </div>
        }
      >
        {children}
      </Suspense>
    </section>
  );
}
