import type { Metadata } from "next";
import DashboardLayoutContent from "@/components/dashboard/DashboardLayoutContent";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DashboardLayoutContent>{children}</DashboardLayoutContent>;
}
