import type { Metadata } from "next";
import { Suspense } from "react";
import Sidebar from "../../components/dashboard/Sidebar";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex min-h-screen bg-white dark:bg-dark-bg">
      <div className="fixed left-0 top-0 z-50">
        <Sidebar />
      </div>
      <section className="flex-1 md:ml-[118px] ml-0 min-h-screen">
        <main
          className="px-20 py-10
          lg:px-10 lg:py-10 
          md:px-6 md:py-8 
          max-md:px-4 max-md:py-4"
        >
          <Suspense
            fallback={
              <div className="text-center dark:text-dark-text">Loading...</div>
            }
          >
            {children}
          </Suspense>
        </main>
      </section>
    </section>
  );
}
